# Generated by Django 3.2.25 on 2024-05-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_rename_scraper_name_service_name'),
        ('Contact', '0002_downloadrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Quote',
        ),
    ]
