# Generated by Django 3.2.25 on 2024-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_rename_contact_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='service',
        ),
        migrations.AddField(
            model_name='quote',
            name='service_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service Category'),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Discount Amount'),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Service Quantity'),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Total After Discount'),
        ),
        migrations.AddField(
            model_name='quote',
            name='service_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Total Price'),
        ),
    ]
