# Generated by Django 3.2.25 on 2024-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0005_auto_20240521_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='service_internal_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
