# Generated by Django 3.2.25 on 2024-04-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='url',
        ),
    ]
