# Generated by Django 3.2.25 on 2024-05-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('internal_note', models.TextField(blank=True, null=True, verbose_name='Internal Note')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Scraper Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per Item (cpi)')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Percentage')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Service.servicecategory', verbose_name='Service Category')),
            ],
        ),
    ]
