# Generated by Django 3.2.25 on 2024-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_rename_scraper_name_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='get_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
