# Generated by Django 3.2.25 on 2024-05-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_service_get_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='get_range',
        ),
    ]
