# Generated by Django 3.2.25 on 2024-05-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_remove_service_get_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='range',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Range'),
        ),
    ]
