# Generated by Django 3.2.25 on 2024-05-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_service_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='range',
        ),
    ]
